### ISSUE TITLE
layout in css

### ISSUE THREAD

**Issue by MarsGotBars** [MarsGotBars/the-client-website#15]
issues hier 🎈

**Comment by ColindeGroot** [comment]
in content block staat een grid. Dit kan ook gemaakt worden met een max width en margin (grid lijkt ons een beetje overbodig).
in je navigatie kan je gebruik maken van een gap ipv losse margins


-Dylan en Colin

**Comment by julia-stevens** [comment]
- Het enige wat ik qua layout kan aanmerken is dat je bij de div `companies-block` flex gebruikt, maar misschien hier beter een grid met 2 rijen? 

- Verder kun je misschien nog kijken naar de mobiele layout?
