### ISSUE TITLE
Idee is dat je een externe stylesheet gebruikt

### ISSUE THREAD

**Issue by rutgerkock** [MarsGotBars/the-client-website#32]
https://github.com/MarsGotBars/the-client-website/blob/337e653e3a9781a218d1aeadb557b77803dd3738/index.html#L2-L10
Idee van de opdracht was dat je een andere stylesheet gebruikt vanuit een andere repo, doe dit :)

**Comment by MarsGotBars** [comment]
staat er nu in!
