### ISSUE TITLE
Kan dit geen ```<p>``` zijn?

### ISSUE THREAD

**Issue by rutgerkock** [MarsGotBars/the-client-website#33]
https://github.com/MarsGotBars/the-client-website/blob/337e653e3a9781a218d1aeadb557b77803dd3738/index.html#L228-L232
Je gebruikt nu een nietszeggend element, probeer waar mogelijk altijd elementen met betekenis te gebruiken, ik geloof dat dit gewoon een ```<p>``` kan zijn.

**Comment by MarsGotBars** [comment]
Weet niet precies welke line je bedoelt, bedoel je de a zonder href? @rutgerkock

**Comment by rutgerkock** [comment]
Nee sorry had iets duidelijker moeten zijn, bedoel de span.
Een span zegt niks, als het gewoon tekst is, maak er een <p> van
