### ISSUE TITLE
Werken met custom-properties en eventueel een ```::after```

### ISSUE THREAD

**Issue by rutgerkock** [MarsGotBars/the-client-website#34]
https://github.com/MarsGotBars/the-client-website/blob/337e653e3a9781a218d1aeadb557b77803dd3738/index.html#L278
Je kan hier ook gewoon custom properties gebruiken, kan je makkelijk de kleur aanpassen met 1 verandering I.P.V. elke regel afgaan. Kan in dit geval misschien ook een svg inladen als ::after?

**Comment by MarsGotBars** [comment]
Dit is een property die mee kwam tijdens het kopieëren vanuit figma, pas deze ook aan vanuit de css maar bedankt!

**Comment by rutgerkock** [comment]
Als je het aanpast vanuit de CSS is deze regel overbodig, haal hem dan weg, lekker bezig!
